### ISSUE TITLE
Suitable for production?

### ISSUE THREAD

**Issue by peachp** [Arro/mongo-airtable#7]
I'm considering to use your tool to pull our entire Airtable base to our **Staging** webserver's MongoDB, from which I will then generate pages for our website. We then deploy all this static content as complete stand-alone ZIP to our **Live** web server.

I already use the official Airtable API JS client, but with your tool I hope to avoid problems with the Airtable API limitations (5 requests per second).

This won't be a big improvement to using the Airtable API directly, because I can delay the API requests and we are OK with waiting 10-30min. However, I'm wondering if at some point I can have the MongoDB directly on our Production and threfore skip generating the static pages on Staging server and then read/write dynamic content (e.g. Orders, User profiles) directly from the MongoDB, which in background will be synced by your tool every 10min or so.

Are you using it for scenarios like this?
Or only to sync our offline copy of the base, like for local development for example?

Asking because I've read this:
*The problem is that sometimes you don't have internet access, so pulling and saving data using their API isn't feasible.*

Thanks for your input!

**Comment by Arro** [comment]
Hey, thanks for considering using my tool!  

I'm using it for scenarios like the one you're describing, yes.  

The part of the readme you quoted... that was the original motivation.  But the general concept of "not having to talk to Airtable too frequently" has been good for development.

I think I may have broken it a few days ago, though, so let me try to fix it first.  Also need to give it some tests.  Will let you know.

**Comment by peachp** [comment]
Hi. Thanks for the info. Meanwhile I built a simple sync script to fit our
needs better.
E.g. to leverage formulas (instead of relying on views) to fetch changed
data every minute. Also I use Mongoose to define some models to be able to
use things like populate().

Good luck with your project!
